# Generated by Django 5.1 on 2024-08-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDS_App', '0002_alter_appdetails_appicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetails',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
